
services:
  publicissues:
    build:
      context: .
      target: dev
    env_file: .env
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: src
          action: sync
          target: /app/src
        - path: public
          action: sync
          target: /app/public
        - path: package.json
          action: rebuild
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mldchan
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=publicissues
